INSERT INTO [ClubLocation] 
VALUES ('CID0','Red-whispered bulbul Q1','Calling all nature enthusiasts and bird lovers in District 1! Discover the captivating Red-Whispered Bulbul and join our exclusive club. Gain expert insights, embark on thrilling expeditions, and contribute to conservation efforts. Connect with fellow bird enthusiasts and celebrate the beauty of these magnificent birds. Contact us or visit our website to become a member today!','LID0');
INSERT INTO [ClubLocation] 
VALUES ('CID1','Red-whispered bulbul Q3','Welcome to the Red-Whispered Bulbul Club in District 3! If you are passionate about birds, this is the perfect club for you. Explore their unique behaviors, habitats, and conservation efforts. Connect with like-minded individuals, participate in workshops, and join us on captivating birdwatching adventures. Contact us or visit our website to become a proud member of the Red-Whispered Bulbul Club in District 3!','LID1');
INSERT INTO [ClubLocation] 
VALUES ('CID2','Red-whispered bulbul Q4','Calling all bird enthusiasts in District 4! Become a part of our Red-Whispered Bulbul Club and discover the wonders of these charming birds. Gain expert knowledge, embark on expeditions, and foster community connections. Contribute to their conservation and celebrate their beauty in the company of fellow bird lovers. Contact us or visit our website to join the Red-Whispered Bulbul Club in District 4 today!','LID2');
INSERT INTO [ClubLocation] 
VALUES ('CID3','Red-whispered bulbul Q10','Attention bird lovers in District 10! Join our exclusive club dedicated to the Red-Whispered Bulbul. Explore their fascinating world through educational workshops, thrilling field trips, and community engagement. Connect with fellow enthusiasts, contribute to conservation efforts, and celebrate the splendor of these magnificent birds. Contact us or visit our website to become a member of the Red-Whispered Bulbul Club in District 10!','LID3');
INSERT INTO [ClubLocation] 
VALUES ('CID4','Red-whispered bulbul Q12','Welcome to the Red-Whispered Bulbul Club in District 12! Immerse yourself in the beauty of these enchanting birds. Discover their habitats, behaviors, and conservation importance through engaging activities, field trips, and workshops. Connect with fellow bird enthusiasts, contribute to their preservation, and build lasting memories. Contact us or visit our website to join the Red-Whispered Bulbul Club in District 12 today!','LID4');
INSERT INTO [ClubLocation] 
VALUES ('CID5','Red-whispered bulbul Q9','Discover the Red-Whispered Bulbul Club in District 9, a haven for bird enthusiasts. Join us to gain expert insights, embark on thrilling expeditions, and participate in educational workshops. Connect with like-minded individuals, contribute to conservation efforts, and celebrate the beauty of these magnificent birds. Contact us or visit our website to become a member today!','LID5');
INSERT INTO [ClubLocation] 
VALUES ('CID6','Red-whispered bulbul Q2','Attention nature lovers and bird enthusiasts in District 2! Immerse yourself in the world of the Red-Whispered Bulbul by joining our club. Experience exciting field trips, educational workshops, and community bonding. Contribute to conservation efforts and deepen your appreciation for these delightful birds. Contact us or visit our website to join the Red-Whispered Bulbul Club in District 2 today!','LID6');
INSERT INTO [ClubLocation] 
VALUES ('CID7','Red-whispered bulbul Q.Dong Da','Attention nature enthusiasts and bird lovers in Đống Đa District! Discover the captivating Red-Whispered Bulbul and become a part of our exclusive club. Gain expert insights, embark on thrilling expeditions, and contribute to conservation efforts. Connect with fellow bird enthusiasts and celebrate the beauty of these magnificent birds. Contact us or visit our website to become a member today!','LID7');
INSERT INTO [ClubLocation] 
VALUES ('CID8','Red-whispered bulbul Q.Ba Dinh','Calling all bird lovers and nature enthusiasts in Ba Đình District! Immerse yourself in the world of the Red-Whispered Bulbul by joining our club. Experience exciting field trips, educational workshops, and community bonding. Contribute to conservation efforts and deepen your appreciation for these delightful birds. Contact us or visit our website to join the Red-Whispered Bulbul Club in Ba Đình District today!','LID8');
INSERT INTO [ClubLocation] 
VALUES ('CID9','Red-whispered bulbul Q.Tay Ho','Welcome to the Red-Whispered Bulbul Club in Tây Hồ District! If you are passionate about birds, this is the perfect club for you. Explore their unique behaviors, habitats, and conservation efforts. Connect with like-minded individuals, participate in workshops, and join us on captivating birdwatching adventures. Contact us or visit our website to become a proud member of the Red-Whispered Bulbul Club in Tây Hồ District today!','LID9');