SELECT TOP (1000) [UID]
      ,[userName]
      ,[fullName]
      ,[phone]
      ,[email]
      ,[password]
      ,[role]
      ,[expiredDate]
      ,[status]
      ,[signupDate]
      ,[MID]
      ,[gender]
  FROM [ChimOwner].[dbo].[User]
