+"<div class='responsive'>"
+"<div class='gallery'>"
+"<a target='_blank' href='img_5terre.jpg'>"
+"<img src='img_5terre.jpg' alt='Cinque Terre' width='600' height='400'></a>"
+"<div class='desc'>Description</div></div></div>"